# -*- coding: utf-8 -*-
"""Predicting Solar Energy Production.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18nbYjON5ZFAYTdjZ6VYDMlTWROCcwtK0

<h1 align="left"><font color=#DE720A><b>Predicting Solar Energy Production</b></font></h1>

<h4 align="left"><font color=#2B9106><b>About this data</b></font></h4>

In this dataset a prominent renewable energy provider dedicated to expanding their solar energy portfolio while ensuring efficient grid integration. They are focused on optimizing project planning, grid integration, and maximizing returns on investment by accurately predicting solar energy production.

<h4 align="left"><font color=#2B9106><b>Objectives :-</b></font></h4>

* __Explore the Dataset__: Analyze environmental and meteorological factors such as solar irradiance, temperature, humidity, wind speed, cloud cover, atmospheric pressure, and other relevant variables that influence solar energy production.

* __Conduct Extensive Exploratory Data Analysis (EDA)__:
  - Perform univariate, bivariate, and multivariate analysis.
  - Identify data distributions, trends, outliers, and feature relationships.
  - Examine correlations between input features and solar energy production.

* __Preprocessing Steps__:
  - Handle missing values.
  - Convert date columns into useful time-based features.
  - Perform feature engineering.
  - Remove unnecessary columns.
  - Separate features and target variable.
  - Identify numerical and categorical features.
  - Build a preprocessing pipeline with encoding and scaling where required.

* __Model Building__:
  * __Solar Energy Production Prediction (Regression)__:
     - Implement regression models such as Linear Regression, Random Forest Regressor, Gradient Boosting Regressor, and Extra Trees Regressor.
     - Compare model performance using R² Score, MAE, MSE, RMSE, and MAPE.
     - Perform Random Forest Hyperparameter Tuning to improve prediction performance.
     - Validate the selected model using Cross-Validation.
     - Evaluate the final model through residual analysis, prediction error plots, and Actual vs Predicted comparisons.

* __Feature Importance & Business Insights__:
  - Identify the most influential features affecting solar energy production.
  - Interpret model results to support efficient solar power forecasting.
  - Provide insights for energy planning, grid management, and renewable energy optimization.

* __Model Deployment Preparation__:
  - Save the trained model using Joblib.
  - Load the saved model for future predictions.
  - Predict solar energy production on unseen data using the finalized model.

<h2 align="left"><font color=#C41205><B>Let's Started :-</font></h2>

<h4 align="left"><font color=#2B9106><b>Step 1 | Import Libraries<b></font></h4>
"""

# Data Manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.cm as cm
import matplotlib.colors as colors

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

# Models
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import ExtraTreesRegressor

# Metrics
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score


# Model Saving
import joblib

"""<h4 align="left"><font color=#2B9106><b>Step 2 | Load Dataset<b></font></h4>"""

df = pd.read_csv("Solar Energy.csv", low_memory=False)

df_copy = df.copy()

"""<h4 align="left"><font color=#2B9106><b>Step 3 | Initial Inspection<b></font></h4>"""

print(df.describe())

print(df.isnull().sum())

print(df.nunique())

"""<h4 align="left"><font color=#2B9106><b>Step 3 | Rename Columns<b></font></h4>"""

df.columns = df.columns.str.strip()

df.rename(columns={
    "Estimated Annual PV Energy Production (kWh)":"Annual_Energy",
    "Estimated PV System Size (kWdc)":"PV_kWdc",
    "PV System Size (kWac)":"PV_kWac",
    "Energy Storage System Size (kWac)":"Storage_kWac",
    "Data Through Date":"Data_Date",
    "Interconnection Date":"Connection_Date",
    "City/Town":"City",
    "Circuit ID":"Circuit_ID",
    "Project ID":"Project_ID",
    "Number of Projects":"Projects"
}, inplace=True)

"""<h4 align="left"><font color=#2B9106><b>Step 4 | Convert Date Columns<b></font></h4>"""

df["Data_Date"] = pd.to_datetime(df["Data_Date"])

df["Connection_Date"] = pd.to_datetime(df["Connection_Date"])

"""<h4 align="left"><font color=#2B9106><b>Step 5 | Feature Engineering<b></font></h4>"""

df["Connection_Year"] = df["Connection_Date"].dt.year
df["Connection_Month"] = df["Connection_Date"].dt.month
df["Connection_Day"] = df["Connection_Date"].dt.day

df["Data_Year"] = df["Data_Date"].dt.year

"""<h4 align="left"><font color=#2B9106><b>Step 6 | Remove Unnecessary Columns<b></font></h4>"""

df.drop(["Project_ID"], axis=1, inplace=True)

"""<h4 align="left"><font color=#2B9106><b>Step 7 | Separate Features<b></font></h4>"""

target = "Annual_Energy"

X = df.drop(target, axis=1)

y = df[target]

"""<h4 align="left"><font color=#2B9106><b>Missing Values Heatmap<b></font></h4>"""

plt.figure(figsize=(12,6))
sns.heatmap(df.isnull(), cbar=False, cmap="viridis")
plt.title("Missing Values Heatmap")
plt.show()

"""<h4 align="left"><font color=#2B9106><b>Step 8 | Numerical & Categorical Columns<b></font></h4>"""

numerical_features = X.select_dtypes(include=np.number).columns

categorical_features = X.select_dtypes(exclude=np.number).columns

print(numerical_features)

print(categorical_features)

"""<h4 align="left"><font color=#2B9106><b>Step 8.1 | Numerical Feature Distribution<b></font></h4>"""

num_cols = df.select_dtypes(include=np.number).columns

df[num_cols].hist(
    figsize=(20,15),
    bins=30,
    edgecolor='black'
)

plt.suptitle("Distribution of Numerical Features")
plt.show()

"""<h4 align="left"><font color=#2B9106><b>Step 9 | Preprocessing Pipeline<b></font></h4>"""

numeric_transformer = Pipeline(

steps=[

("imputer", SimpleImputer(strategy="median")),

("scaler", StandardScaler())

])

categorical_transformer = Pipeline(

steps=[

("imputer", SimpleImputer(strategy="most_frequent")),

("encoder", OneHotEncoder(handle_unknown="ignore"))

])

preprocessor = ColumnTransformer(

transformers=[

("num", numeric_transformer, numerical_features),

("cat", categorical_transformer, categorical_features)

])

"""<h4 align="left"><font color=#2B9106><b>Boxplots (Outlier Detection)<b></font></h4>"""

n = len(num_cols)

# Decide layout: 1 row if few columns, multiple rows if many
rows = 1 if n <= 3 else 2
cols = (n + rows - 1) // rows  # distribute evenly

fig, axes = plt.subplots(rows, cols, figsize=(3*cols, 2.5*rows))  # smaller size
axes = axes.flatten()

for i, col in enumerate(num_cols):
    sns.boxplot(x=df[col], color='skyblue', ax=axes[i])
    axes[i].set_title(f"Boxplot of {col}", fontsize=10)

# Remove unused axes if any
for j in range(i+1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

"""<h4 align="left"><font color=#2B9106><b>Correlation Heatmap<b></font></h4>"""

plt.figure(figsize=(14,10))

sns.heatmap(
    df[num_cols].corr(),
    annot=True,
    cmap="viridis",
    fmt=".2f"
)

plt.title("Correlation Matrix")
plt.show()

"""<h4 align="left"><font color=#2B9106><b>Top Cities by Energy Production<b></font></h4>"""

top_city = df.groupby("City")["Annual_Energy"].mean().sort_values(ascending=False).head(10)

plt.figure(figsize=(12,6))

sns.barplot(
    x=top_city.values,
    y=top_city.index,
    palette="viridis"
)

plt.title("Top 10 Cities by Average Annual Energy")
plt.xlabel("Average Energy")
plt.ylabel("City")
plt.show()

"""<h4 align="left"><font color=#2B9106><b>Step 10 | Train-Test Split<b></font></h4>"""

X_train, X_test, y_train, y_test = train_test_split(

X,
y,
test_size=0.2,
random_state=42

)

"""<h4 align="left"><font color=#2B9106><b>Step 11 | Model<b></font></h4>

<h4 align="left"><font color=#2B9106><b>Step 11.1 | Linear Regression<b></font></h4>
"""

lr = Pipeline([

("preprocessor", preprocessor),

("model", LinearRegression())

])

lr.fit(X_train,y_train)

pred_lr = lr.predict(X_test)

print("MAE :",mean_absolute_error(y_test,pred_lr))

print("RMSE :",np.sqrt(mean_squared_error(y_test,pred_lr)))

print("R2 :",r2_score(y_test,pred_lr))

"""<h4 align="left"><font color=#2B9106><b>Step 11.2 | Random Forest<b></font></h4>"""

rf = Pipeline([

("preprocessor", preprocessor),

("model", RandomForestRegressor(

random_state=42

))

])

rf.fit(X_train,y_train)

pred_rf = rf.predict(X_test)

print("MAE :",mean_absolute_error(y_test,pred_rf))

print("RMSE :",np.sqrt(mean_squared_error(y_test,pred_rf)))

print("R2 :",r2_score(y_test,pred_rf))

"""<h4 align="left"><font color=#2B9106><b>Step 11.3 | Gradient Boosting<b></font></h4>"""

gb = Pipeline([

("preprocessor", preprocessor),

("model", GradientBoostingRegressor(

random_state=42

))

])

gb.fit(X_train,y_train)

pred_gb = gb.predict(X_test)

print("MAE :",mean_absolute_error(y_test,pred_gb))

print("RMSE :",np.sqrt(mean_squared_error(y_test,pred_gb)))

print("R2 :",r2_score(y_test,pred_gb))

"""<h4 align="left"><font color=#2B9106><b>Step 11.4 | Extra Trees<b></font></h4>"""

et = Pipeline([

("preprocessor", preprocessor),

("model", ExtraTreesRegressor(

random_state=42

))

])

et.fit(X_train,y_train)

pred_et = et.predict(X_test)

print("MAE :",mean_absolute_error(y_test,pred_et))

print("RMSE :",np.sqrt(mean_squared_error(y_test,pred_et)))

print("R2 :",r2_score(y_test,pred_et))

"""<h4 align="left"><font color=#2B9106><b>Step 12 | Model Comparison<b></font></h4>"""

results = pd.DataFrame({

"Model":["Linear Regression",

"Random Forest",

"Gradient Boosting"

],

"R2":[

r2_score(y_test,pred_lr),

r2_score(y_test,pred_rf),

r2_score(y_test,pred_gb)

],

"MAE":[

mean_absolute_error(y_test,pred_lr),

mean_absolute_error(y_test,pred_rf),

mean_absolute_error(y_test,pred_gb)

]

})

print(results.sort_values("R2",ascending=False))

"""<h4 align="left"><font color=#2B9106><b>Step 13 | Hyperparameter Tuning (Random Forest)<b></font></h4>"""

# It has been taken too much time to run, My laptop cant run it because of huge data, If i could run this Hyperparameter tunning, it will give a better accuracy.
# from sklearn.model_selection import RandomizedSearchCV

# random_grid = {
#     "model__n_estimators": [100, 200, 300],
#     "model__max_depth": [10, 20, None],
#     "model__min_samples_split": [2, 5],
#     "model__min_samples_leaf": [1, 2]
# }

# random_search = RandomizedSearchCV(
#     rf,
#     param_distributions=random_grid,
#     n_iter=10,   # try only 10 random combos
#     cv=3,
#     scoring="r2",
#     n_jobs=-1,
#     random_state=42
# )

# random_search.fit(X_train, y_train)
# print(random_search.best_params_)

"""<h4 align="left"><font color=#2B9106><b>Step 14 | Select the Best Model<b></font></h4>"""

# Select the best model
best_model = rf

print("Best Model Selected: Random Forest")

#To get prediction error, error% etc
y_pred = best_model.predict(X_test)
prediction_df = pd.DataFrame({
    "Prediction ID": range(1, len(y_test) + 1),
    "Actual Energy": y_test.values,
    "Predicted Energy": y_pred
})

prediction_df["Prediction Error"] = (
    prediction_df["Actual Energy"] -
    prediction_df["Predicted Energy"]
)

prediction_df["Error %"] = (
    prediction_df["Prediction Error"] /
    prediction_df["Actual Energy"]
) * 100

prediction_df.to_csv("predictions.csv", index=False)

"""<h4 align="left"><font color=#2B9106><b>Step 15 | Cross Validation<b></font></h4>"""

# scores = cross_val_score(
#     best_model,
#     X,
#     y,
#     cv=3,
#     scoring='r2',
#     n_jobs=-1
# )

# print("Cross Validation Scores:")
# print(scores)

# print("\nAverage R² Score:", scores.mean())

"""<h4 align="left"><font color=#2B9106><b>Step 16 | Final Model Evaluation<b></font></h4>"""

y_pred = best_model.predict(X_test)

"""<h4 align="left"><font color=#2B9106><b>Step 16.1 | Calculate Metrics<b></font></h4>"""

mae = mean_absolute_error(y_test, y_pred)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))

r2 = r2_score(y_test, y_pred)

print("Final Model Performance")
print("-"*40)

print(f"MAE  : {mae:.2f}")

print(f"RMSE : {rmse:.2f}")

print(f"R²   : {r2:.4f}")

"""<h4 align="left"><font color=#2B9106><b>Step 16.2 | Actual vs Predicted Plot<b></font></h4>"""

plt.figure(figsize=(6,4))

plt.scatter(
    y_test,
    y_pred,
    alpha=0.6
)

plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    color='red'
)

plt.xlabel("Actual Energy Production")

plt.ylabel("Predicted Energy Production")

plt.title("Actual vs Predicted")

plt.show()

"""<h4 align="left"><font color=#2B9106><b>Step 16.3 | Residual Plot<b></font></h4>"""

residuals = y_test - y_pred

plt.figure(figsize=(6,4))

plt.scatter(
    y_pred,
    residuals,
    alpha=0.6
)

plt.axhline(
    y=0,
    color='red',
    linestyle='--'
)

plt.xlabel("Predicted Values")

plt.ylabel("Residuals")

plt.title("Residual Plot")

plt.show()

"""<h4 align="left"><font color=#2B9106><b>Step 16.4 | Residual Distribution<b></font></h4>"""

plt.figure(figsize=(6,3))

sns.histplot(
    residuals,
    kde=True
)

plt.title("Residual Distribution")

plt.show()

"""<h4 align="left"><font color=#2B9106><b>Step 16.5 | Prediction Error Plot<b></font></h4>"""

errors = y_test - y_pred

plt.figure(figsize=(6,4))

plt.scatter(
    y_pred,
    errors,
    alpha=0.6
)

plt.axhline(
    y=0,
    color='red',
    linestyle='--'
)

plt.xlabel("Predicted Values")

plt.ylabel("Prediction Error")

plt.title("Prediction Error Plot")

plt.show()

"""<h4 align="left"><font color=#2B9106><b>Step 17 | Feature Importance<b></font></h4>"""

feature_names = best_model.named_steps[
    'preprocessor'
].get_feature_names_out()

importance = best_model.named_steps[
    'model'
].feature_importances_

importance_df = pd.DataFrame({

    "Feature": feature_names,

    "Importance": importance

})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
)

print(importance_df.head(20))

feature_names_processed = best_model.named_steps[
    'preprocessor'
].get_feature_names_out()

importance = pd.DataFrame({
    "Feature": feature_names_processed,
    "Importance": best_model.named_steps['model'].feature_importances_
})

importance = importance.sort_values(
    "Importance",
    ascending=False
)

importance.to_csv("feature_importance.csv", index=False)

"""<h4 align="left"><font color=#2B9106><b>Step 17.1 | Feature Importance Plot<b></font></h4>"""

top20 = importance_df.head(20)

plt.figure(figsize=(7,5))

sns.barplot(
    data=top20,
    x="Importance",
    y="Feature"
)

plt.title("Top 20 Important Features")

plt.show()

"""<h4 align="left"><font color=#2B9106><b>Step 17.2 | Training vs Testing R²<b></font></h4>"""

train_r2 = best_model.score(X_train, y_train)
test_r2 = best_model.score(X_test, y_test)

print("Train R² :", train_r2)
print("Test R² :", test_r2)

"""<h4 align="left"><font color=#2B9106><b>Step 17.3 | Error Percentage (MAPE)<b></font></h4>"""

from sklearn.metrics import mean_absolute_percentage_error

mape = mean_absolute_percentage_error(y_test, y_pred)

print("MAPE:", mape)

"""<h4 align="left"><font color=#2B9106><b>Step 16 | Save Model<b></font></h4>"""

joblib.dump(
    best_model,
    "solar_energy_prediction.pkl"
)

print("Model Saved Successfully!")

fitted_scaler = best_model.named_steps['preprocessor'].named_transformers_['num'].named_steps['scaler']
joblib.dump(fitted_scaler, "scaler.pkl")
print("Scaler Saved Successfully!")

"""<h4 align="left"><font color=#2B9106><b>Step 16 | Load Model<b></font></h4>"""

model = joblib.load(
    "solar_energy_prediction.pkl"
)

print("Model Loaded Successfully!")

"""<h4 align="left"><font color=#2B9106><b>Step 17 | Predict on New Data<b></font></h4>"""

sample = X.iloc[[0]]

prediction = model.predict(sample)

print("Predicted Annual Energy Production (kWh):")

print(prediction[0])

"""<h4 align="left"><font color=#2B9106><b>Business Insights</b></font></h4>

* The model accurately predicts annual solar energy production.

* Energy providers can estimate future electricity generation
   before installing new solar systems.

* Investors can identify high-performing solar projects,
   helping maximize return on investment (ROI).

* Utility companies can improve grid planning by forecasting
   expected solar power generation.

* System designers can optimize PV system capacity to increase
   annual energy output.

* The model supports data-driven decision-making for renewable
   energy expansion and sustainable infrastructure planning.

<p align="center"><font color=blue; size=150px><b>THE END</b></font></p>
"""

import pandas as pd

# Assuming your DataFrame is called df
df.to_csv('solar_data.csv', index=False)

print("CSV file saved as solar_data.csv in your project folder")
